FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /leoxy ./app/cli

FROM alpine:3.21

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /leoxy /app/bin/leoxy
COPY example/config.yaml /app/leoxy/config.yaml

EXPOSE 8080

CMD ["/app/bin/leoxy"]
