server:
  port: "8080"

upstream:
  - name: "Backend"
    path: /api
    ip: true
    body: 10 # By MB only
    limit_request: 100
    server_url: "http://localhost:60459"

  - name: "Frontend"
    path: /
    server_url: "http://localhost:3000"
